export const GOOGLE_SHEET_DEFAULTS = {
  gsheets_enabled: 'false',
  gsheets_auth_mode: 'service_account',
  gsheets_client_email: '',
  gsheets_private_key: '',
  gsheets_client_id: '',
  gsheets_client_secret: '',
  gsheets_refresh_token: '',
  gsheets_buyers_spreadsheet_id: '',
  gsheets_buyers_raw_imports_tab: 'buyers_raw_imports',
  gsheets_buyers_master_tab: 'buyers_master',
  gsheets_buyers_dedupe_review_tab: 'buyers_dedupe_review',
  gsheets_advisor_folders_json: '[]',
  gsheets_listings_spreadsheet_id: '',
  gsheets_listings_master_tab: 'listings_master',
  gsheets_matching_spreadsheet_id: '',
  gsheets_match_results_tab: 'match_results',
  gsheets_top50_tab: 'top_50_by_listing',
  gsheets_match_settings_tab: 'match_settings'
};

export const GOOGLE_SHEET_TAB_OPTIONS = {
  buyers: ['buyers_raw_imports', 'buyers_master', 'buyers_dedupe_review'],
  listings: ['listings_master'],
  matching: ['match_results', 'top_50_by_listing', 'match_settings']
};

export const BUYERS_MASTER_COLUMNS = [
  'buyer_id',
  'created_at',
  'updated_at',
  'is_active',
  'source_advisor_ids',
  'source_advisor_names',
  'source_file_names',
  'first_name',
  'last_name',
  'full_name',
  'email',
  'normalized_email',
  'phone',
  'normalized_phone',
  'company',
  'city',
  'state_province',
  'country',
  'geo_normalized',
  'buyer_type',
  'strategic_or_financial',
  'industry_interest_raw',
  'normalized_industries',
  'acquisition_criteria_raw',
  'normalized_keywords',
  'geographic_focus_raw',
  'normalized_geographies',
  'deal_size_min',
  'deal_size_max',
  'revenue_min',
  'revenue_max',
  'ebitda_min',
  'ebitda_max',
  'capital_available',
  'source_of_funds',
  'last_contact_date',
  'freshness_score',
  'tags',
  'notes',
  'email_dedupe_key',
  'phone_dedupe_key',
  'name_company_dedupe_key',
  'manual_review_flag'
];

export const BUYERS_RAW_IMPORTS_COLUMNS = [
  'raw_import_id',
  'import_batch_id',
  'source_file_name',
  'source_advisor_id',
  'source_advisor_name',
  'imported_at',
  'raw_first_name',
  'raw_last_name',
  'raw_full_name',
  'raw_email',
  'raw_phone',
  'raw_company',
  'raw_city',
  'raw_state',
  'raw_country',
  'raw_tags',
  'raw_notes',
  'raw_acquisition_criteria',
  'raw_industry_interest',
  'raw_geographic_focus',
  'raw_deal_size',
  'raw_capital_available',
  'raw_last_contact_date',
  'raw_custom_fields_json',
  'processing_status',
  'processing_notes'
];

export const BUYERS_DEDUPE_REVIEW_COLUMNS = [
  'dedupe_case_id',
  'candidate_buyer_id_1',
  'candidate_buyer_id_2',
  'similarity_reason',
  'similarity_score',
  'suggested_action',
  'reviewer_status',
  'reviewer_notes',
  'reviewed_at'
];

export const LISTINGS_MASTER_COLUMNS = [
  'listing_id',
  'created_at',
  'updated_at',
  'is_active',
  'source_site',
  'source_url',
  'source_listing_key',
  'listing_title',
  'company_name',
  'industry',
  'sub_industry',
  'industry_normalized',
  'keywords_normalized',
  'city',
  'state_province',
  'country',
  'geo_normalized',
  'asking_price',
  'revenue',
  'ebitda',
  'sde_cash_flow',
  'employees',
  'established_year',
  'inventory_included',
  'real_estate_included',
  'reason_for_sale',
  'summary',
  'listing_status',
  'listing_dedupe_key',
  'manual_review_flag'
];

export const MATCH_RESULTS_COLUMNS = [
  'match_id',
  'match_run_id',
  'match_date',
  'listing_id',
  'buyer_id',
  'overall_score',
  'industry_score',
  'geo_score',
  'size_score',
  'revenue_score',
  'ebitda_score',
  'keyword_score',
  'freshness_score',
  'rank_for_listing',
  'rank_for_buyer',
  'match_bucket',
  'explanation'
];

export const TOP_50_COLUMNS = [
  'listing_id',
  'listing_title',
  'buyer_rank',
  'buyer_id',
  'buyer_name',
  'buyer_company',
  'buyer_email',
  'buyer_phone',
  'overall_score',
  'industry_score',
  'geo_score',
  'size_score',
  'keyword_score',
  'explanation',
  'generated_at'
];
